[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mst-sbt-mint"
version = "0.1.0"
description = "Mustree Network SBT(Soulbound Token) minting SDK"
authors = [
    { name = "JaeHyun Kim", email = "passiontom@anver.com" }
]
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
    "web3>=7.0.0",
]

[project.urls]
Homepage = "https://github.com/your-org/mst-sbt-mint"
